import { StyleSheet, Dimensions, Platform } from 'react-native';
import { Theme } from '../contexts/ThemeContext';

const { width, height } = Dimensions.get('window');

export const getPhoneStyles = (theme: Theme) => {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingTop: 50,
      paddingBottom: 16,
    },
    headerSpacer: {
      flex: 1,
    },
    menuButton: {
      padding: 8,
      borderRadius: 20,
    },
    menuIcon: {
      fontSize: 30,
      color: theme.colors.text,
      fontWeight: 'bold',
      transform: [{ rotate: '180deg' }],
    },
    safeArea: {
      flex: 1,
    },
    keyboardAvoidingView: {
      flex: 1,
      paddingHorizontal: 32,
    },
    content: {
      flex: 1,
      justifyContent: 'center',
      paddingVertical: 40,
    },
    title: {
      fontSize: 22,
      fontWeight: '600',
      color: theme.colors.text,
      textAlign: 'center',
      marginBottom: 12,
      letterSpacing: 0.5,
    },
    subtitle: {
      fontSize: 15,
      color: theme.colors.textSecondary,
      textAlign: 'center',
      marginBottom: 12,
      lineHeight: 22,
      paddingHorizontal: 20,
    },
    helpLink: {
      fontSize: 16,
      color: theme.colors.link,
      textAlign: 'center',
      textDecorationLine: 'underline',
      marginBottom: 50,
      fontWeight: '500',
    },
    inputContainer: {
      marginBottom: 40,
    },
    phoneInputContainer: {
      marginBottom: 8,
    },
    phoneInputRow: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'transparent',
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.border,
      paddingBottom: 16,
      paddingTop: 16,
      paddingHorizontal: 0,
    },
    countrySection: {
      paddingRight: 20,
      paddingLeft: 0,
      borderRightWidth: 1,
      borderRightColor: theme.colors.border,
      marginRight: 20,
      minWidth: 60,
    },
    countryCodeText: {
      fontSize: 16,
      color: theme.colors.text,
      fontWeight: '500',
      letterSpacing: 0.5,
    },
    phoneInput: {
      fontSize: 16,
      color: theme.colors.text,
      paddingVertical: 0,
      paddingHorizontal: 0,
      backgroundColor: 'transparent',
      flex: 1,
      borderWidth: 0,
      fontWeight: '400',
    },
    phoneInputFocused: {
      borderBottomColor: theme.colors.primary,
      borderBottomWidth: 1,
    },
    errorText: {
      fontSize: 14,
      color: '#FF6B6B',
      marginTop: 12,
      marginLeft: 0,
      fontWeight: '500',
    },
    button: {
      backgroundColor: theme.colors.primary,
      paddingVertical: 16,
      paddingHorizontal: 32,
      borderRadius: 8,
      width: '100%',
      alignItems: 'center',
      marginTop: 32,
      shadowColor: theme.colors.primary,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 3,
    },
    buttonDisabled: {
      backgroundColor: theme.colors.border,
      shadowOpacity: 0,
      elevation: 0,
    },
    buttonText: {
      color: '#FFFFFF',
      fontSize: 17,
      fontWeight: '600',
      letterSpacing: 0.5,
    },
    buttonTextDisabled: {
      color: theme.colors.textSecondary,
    },
    bottomButtonContainer: {
      paddingHorizontal: 32,
      paddingVertical: 20,
      paddingBottom: Platform.OS === 'ios' ? 34 : 30,
      backgroundColor: theme.colors.background,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'flex-start',
      alignItems: 'flex-end',
      paddingTop: 60,
      paddingRight: 16,
    },
    menuContainer: {
      backgroundColor: theme.colors.surface,
      borderRadius: 8,
      paddingVertical: 8,
      minWidth: 120,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    menuItem: {
      paddingHorizontal: 16,
      paddingVertical: 12,
    },
    menuItemText: {
      fontSize: 16,
      color: theme.colors.text,
      fontWeight: '500',
    },
    dialogOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 20,
    },
    confirmationDialog: {
      backgroundColor: '#FFFFFF',
      borderRadius: 12,
      padding: 24,
      width: '100%',
      maxWidth: 320,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 4,
      },
      shadowOpacity: 0.25,
      shadowRadius: 8,
      elevation: 8,
    },
    dialogTitle: {
      fontSize: 16,
      color: '#000000',
      fontWeight: '500',
      marginBottom: 12,
      textAlign: 'center',
    },
    phoneNumberText: {
      fontSize: 18,
      color: '#000000',
      fontWeight: '600',
      textAlign: 'center',
      marginBottom: 16,
    },
    confirmationQuestion: {
      fontSize: 16,
      color: '#000000',
      textAlign: 'center',
      marginBottom: 24,
      lineHeight: 22,
    },
    dialogButtons: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 12,
    },
    editButton: {
      flex: 1,
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: '#E0E0E0',
      alignItems: 'center',
    },
    editButtonText: {
      fontSize: 16,
      color: '#000000',
      fontWeight: '500',
    },
    okButton: {
      flex: 1,
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderRadius: 8,
      backgroundColor: theme.colors.primary,
      alignItems: 'center',
    },
    okButtonText: {
      fontSize: 16,
      color: '#FFFFFF',
      fontWeight: '600',
    },
    loadingDialog: {
      backgroundColor: '#FFFFFF',
      borderRadius: 12,
      padding: 24,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 4,
      },
      shadowOpacity: 0.25,
      shadowRadius: 8,
      elevation: 8,
    },
    loadingSpinner: {
      width: 24,
      height: 24,
      borderRadius: 12,
      borderWidth: 3,
      borderColor: theme.colors.primary,
      borderTopColor: 'transparent',
      marginRight: 12,
    },
    loadingText: {
      fontSize: 16,
      color: '#000000',
      fontWeight: '500',
    },
    // Country Picker Styles
    countrySelector: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 12,
      paddingHorizontal: 16,
      backgroundColor: theme.colors.surface,
      borderRadius: 8,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    countryFlag: {
      fontSize: 24,
      marginRight: 12,
    },
    countryName: {
      flex: 1,
      fontSize: 16,
      color: theme.colors.text,
      fontWeight: '500',
    },
    countryCode: {
      fontSize: 16,
      color: theme.colors.textSecondary,
      fontWeight: '500',
    },
    countryPickerOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 20,
    },
    countryPickerContainer: {
      backgroundColor: theme.colors.surface,
      borderRadius: 12,
      maxHeight: '80%',
      width: '100%',
      maxWidth: 400,
    },
    countryPickerHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingVertical: 16,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.border,
    },
    countryPickerTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: theme.colors.text,
    },
    countryPickerClose: {
      padding: 8,
    },
    countryPickerCloseText: {
      fontSize: 18,
      color: theme.colors.textSecondary,
    },
    countryItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingVertical: 16,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.border,
    },
    countryItemSelected: {
      backgroundColor: theme.colors.background,
    },
    countryItemFlag: {
      fontSize: 24,
      marginRight: 12,
    },
    countryItemName: {
      flex: 1,
      fontSize: 16,
      color: theme.colors.text,
    },
    countryItemCode: {
      fontSize: 16,
      color: theme.colors.textSecondary,
    },
  });
};
